### PR TITLE
fix: Remove childrenWithOverriddenStyle.

### PR DESCRIPTION
**Pull request by troZee**
# Summary
We don't need to override styles for each page. This should be handled outside the lib. 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅   |
| Android |    ✅  |

## Checklist

- [x] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by troZee** [comment]
> Are we sure we do not need it ?
I think, that each view should not be absolute. Children view should relay on its parent. 

> This was taken from the core. I am just wondering if this can introduce a breaking change or if this was done for some specific reason.

I was considering a case, when children view would be just only `ImageView`, then it should be wrapped this `View` tag.  In above case, we added ability to use other View Component than `View`, so dev can decide what should be passed. Because I changed behaviour of children view layouting, so probably it can breaks some views.

I add on hold label, because I need to more test it

**Comment by troZee** [comment]
@ferrannp 
I've checked this code 
```
        <ViewPager
          style={styles.viewPager}
          initialPage={0}
          scrollEnabled={this.state.scrollEnabled}
          onPageScroll={this.onPageScroll}
          onPageSelected={this.onPageSelected}
          onPageScrollStateChanged={this.onPageScrollStateChanged}
          pageMargin={10}
          // Lib does not support dynamically orientation change
          orientation="horizontal"
          // Lib does not support dynamically transitionStyle change
          transitionStyle="scroll" 
          ref={this.viewPager}>
            <Image
            source={{uri: 'https://apod.nasa.gov/apod/image/1410/20141008tleBaldridge001h990.jpg'}}
            />
            <Image
            source={{uri: 'https://apod.nasa.gov/apod/image/1410/20141008tleBaldridge001h990.jpg'}}
          />
          <Text>Some text</Text>
        />
        </ViewPager>
```
And for Images it works well, but for text Red Screen appeared. So, it is better to do above checking.

**Comment by ferrannp** [comment]
> So, it is better to do above checking.

What do you mean?

**Comment by troZee** [comment]
I check each React Node, if it conforms to <View />, if not warning will appeared. I removed code, which is responsible for overriding style for each child.

**Comment by ferrannp** [comment]
I guess with this https://github.com/react-native-community/react-native-viewpager/pull/87 we have enough @troZee ?

**Pull request closed without merging**
